### PR TITLE
OTC-874: Query for enrolment officers locations.

### PR DESCRIPTION
**Pull request by wzglinieckisoldevelo**
Ticket: https://openimis.atlassian.net/browse/OTC-874

Changes:
- Query added enrolment officers locations.

### CODE REVIEW

**Review by malinowskikam — APPROVED** [review]
Looks good

**Comment by delcroip** [comment]
@wzglinieckisoldevelo  should it be reviewed ?

**Comment by wzglinieckisoldevelo** [comment]
@delcroip It turned out that this query was not needed. I asked the question under the ticket if we should merge it. It could be useful at some point. But as I mentioned, right now is not used.

**Comment by wzglinieckisoldevelo** [comment]
@delcroip I've just changed the status of this PR, so if you think it could be useful, you can merge it.

**Review by dborowiecki — APPROVED** [review]
I think this query looks fine, even if it's not used at the moment by FE we should keep it.

**Pull request merged**
